---
-name: Restricting Sudo Access
  hosts: linux
  become: yes
  tasks:
    -name: Get users list
      command: "getent group wheel"
      register: wheel_group_output
      changed_when: false

    -name: Removal of Users
      command: "gpasswd -d {{ item }} wheel"
      loop: "{{ wheel_group.stdout.split(':')[-1].split(',') }}"
      
    -name: Remove Extra Users
      user:
        name: "{{ item }}"
        groups: "{{ (item in ['user1', 'user2']) | ternary('wheel', '') }}"
        append: no
      loop: ""{{ wheel_users }}"
      when: item not in ['user1', 'user2']
      ignore_errors: yes
        
